export { client } from './client'
export { default as queryOwnerInfo } from './query/info.gql'
export { default as queryIssueList } from './query/issueList.gql'
export { default as queryPostCount } from './query/postCount.gql'
export { default as queryPostDetail } from './query/postDetail.gql'
export { default as search } from './query/searchContent.gql'
