import {
  NextPage,
  GetStaticPaths,
  GetStaticProps
} from 'next'
import Head from 'next/head'
import React from 'react'
import { client, queryPostCount, queryPostDetail } from '../../apollo'
import config from '../../config'

export const getStaticPaths: GetStaticPaths<any> = async () => {
  const { data } = await client.query({query: queryPostCount, variables: {
    name: 'blog',
    owner: 'wmasfoe'
  }})
  const res = []
  for(let i = 1; i <= data.repository.issues.totalCount; i++) {
    res.push(`/post/${i}`)
  }
  return {
    paths: res,
    fallback: 'blocking'
  };
}

export const getStaticProps: GetStaticProps<{}> = async ({params}) => {
  try {
    const { data } = await client.query({query: queryPostDetail, variables: {
      postId: +(params?.id || 1),
      owner: 'wmasfoe',
      repoName: 'blog'
    }})
    return {
      props: {
        data
      },
      revalidate: 1000 * 60 * 60 * 24 // 每天更新缓存
    }
  } catch (e) {
    return {
      props: {
        data: null
      },
      revalidate: 1000 * 60 * 60 * 24 // 每天更新缓存
    }
  }
}

const Posts: NextPage = (props: any) => {
  console.log('props ===', props)
  return (
    <div>
      <Head>
        <title>posts</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <a href={config.siteUrl}>HOME</a>
      <div>posts</div>
    </div>
  )
}

export default Posts
