import {
  NextPage,
} from 'next'
import Head from 'next/head'
import React from 'react'
import config from '../../config'

const Posts: NextPage = (props: any) => {
  return (
    <div>
      <Head>
        <title>posts</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <a href={config.siteUrl}>HOME</a>

      <div>posts</div>

      {
        Object.keys(props.info || []).map((item: string) => {
          return <React.Fragment key={item}>
            <div>
              {item}:
            </div>
            <div>
              {props.info[item]}
            </div>
          </React.Fragment>
        })
      }
    </div>
  )
}

export default Posts
