import {
  NextPage,
} from 'next'
import Head from 'next/head'
import Link from 'next/link'
import React from 'react'
import Banner from '../components/Banner'

const Post: NextPage = (props: any) => {
  return (
    <div>
      <Head>
        <title>About Me.</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Banner url='/home-bg.jpeg' title='About me.' text='我只想躺平.' alt='about me.' />
      <Link href='/'>Home</Link>
    </div>
  )
}

export default Post
