import {
  NextPage,
  GetStaticProps,
  GetStaticPropsContext,
} from 'next'
import Head from 'next/head'
import React, { useContext } from 'react'
import { ConfigContext, ConfigType } from './_app'
import useInfo from '../hook/useInfo'
import styles from '../styles/Home.module.css'
import { client } from '../apollo/client'
import info from '../apollo/info.gql'

export const getStaticProps: GetStaticProps<{}> = async (ctx: GetStaticPropsContext) => {
  const { data } = await client.query({query: info})
  return {
    props: {
      info: data?.viewer ? {...(data.viewer)} : data
    },
  }
}

const Home: NextPage = (props: any) => {
  const config = useContext<ConfigType>(ConfigContext);
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <a href={config.siteUrl}>HOME</a>
      {
        Object.keys(props.info || []).map((item: string) => {
          return <React.Fragment key={item}>
            <div>
              {item}:
            </div>
            <div>
              {props.info[item]}
            </div>
          </React.Fragment>
        })
      }
    </div>
  )
}

export default Home
