import type { NextPage, GetServerSideProps } from 'next'
import Head from 'next/head'
import { useQuery, gql } from '@apollo/client'
import { client } from './_app'
import info from '../apollo/info.gql'
import styles from '../styles/Home.module.css'

export const getServerSideProps: GetServerSideProps<{
  avatarUrl: string,
  login: string,
  location: string | null,
  isDeveloperProgramMember: boolean,
  name: string,
  resourcePath: string,
  loading: boolean
}> = async () => {
  const { data, loading } = await client.query({query: gql`${info}`})

  return {
    props: {
      ...(data?.viewer || data || {}),
      loading,
    },
  }
}

const Home: NextPage = (props: any) => {
  console.log(props)

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        Jiaqi.Li
      </div>
      <div>
        Lingyan.Liu
      </div>
    </div>
  )
}

export default Home
