import {
  NextPage,
  GetStaticProps,
  GetStaticPropsContext,
} from 'next'
import Link from 'next/link'
import Head from 'next/head'
import React from 'react'
import config from '../config'
import styles from '../styles/Home.module.css'
import { client } from '../apollo/client'
import info from '../apollo/info.gql'

export const getStaticProps: GetStaticProps<{}> = async (ctx: GetStaticPropsContext) => {
  const { data } = await client.query({query: info})
  return {
    props: {
      info: data?.viewer ? {...(data.viewer)} : data
    },
    // ISR
    revalidate: 1000 * 60 * 60 * 24 // 一天更新一次
  }
}

const Home: NextPage = (props: any) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Link href='/about'>About</Link>
    </div>
  )
}

export default Home
